# Default values for htcondor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

CONDOR_HOST:
CCB_HOST:
PROXY_CACHE:
PROXY_CACHE_Port: 30080
NETWORK_INTERFACE:

SLOT_TYPE_1: cpus=1, mem=2000

LOWPORT: 31024
HIGHPORT: 32048

spool_size: 5Gi
spool_size_claim: 4Gi
spool_host_path: /tmp/

condor_image: dodasts/htcondor:fermi

nfs:
  enabled: false
  size: 1Mi
  server: DUMMY
  path: "/"

cvmfs:
  enabled: false

IAM_TOKEN:
IAM_CLIENT_ID:
IAM_CLIENT_SECRET:
PROXY_AUDIENCE: "https://dodas-tts.cloud.cnaf.infn.it"
PROXY_TTS: "https://dodas-tts.cloud.cnaf.infn.it"
PROXY_IAM_ENDPOINT: "https://dodas-iam.cloud.cnaf.infn.it/"
PROXY_CREDENTIAL_ENDPOINT: "https://dodas-tts.cloud.cnaf.infn.it/api/v2/iam/credential"

tts_image: "dodasts/ttscache:v1.1.0-dodas"
